### ISSUE TITLE
Chunked payments: use TCP congestion control algorithm for adjusting the chunk size?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-psk2#13]
Currently, the PSK2 sender uses multiplication and division by a constant factor to [increase](https://github.com/interledgerjs/ilp-protocol-psk2/blob/master/src/sender.ts#L617) or [decrease](https://github.com/interledgerjs/ilp-protocol-psk2/blob/master/src/sender.ts#L639-L641) the chunk size based on whether transfers succeed or fail. I think we may be able to take inspiration from or directly copy one of the TCP congestion control algorithms to make the sender adjust its chunk size faster and smarter.

In general, the reason to adjust the chunk size is to find the Maximum Payment Size (MPS) that the path can support, and thus send chunked payments as quickly as possible. There will likely be a fixed upper bound on the MPS (i.e. some connector will just never process payments larger than a certain amount). The temporary MPS may change based on how much bandwidth connectors allocate to one another and the endpoints, how quickly balances are settled, and whether there are other applications sending through the same path. This seems similar to how TCP attempts to find how much data it can send through the network without clogging it up or hogging all of the bandwidth from other applications.

I'm not an expert on TCP but looking at [TCP CUBIC](http://www4.ncsu.edu/~rhee/export/bitcp/cubic-paper.pdf), it seems like the payment chunk size might be analogous to the TCP window size. ILP rejections and timeouts could be treated like IP packet loss. It seems like we could use CUBIC's algorithm for searching for the maximum window size and probing in case the maximum changes.

Anyone who understands TCP better want to weigh in on whether this is an appropriate analogy?

**Comment by nappzter** [comment]
I am not an expert either - but based on what I know about TCP BIC vs CUBIC... where ACKs are not required by CUBIC (only dependent on the last congestion event - it would seem that CUBIC algorithm would be more efficient where you need to "chunk payments as quickly as possible".
