### ISSUE TITLE
Add key ID when generating address and secret?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-psk2#17]
@sharafian asked for a way to specify something like a `keyId` when calling `Receiver.generateAddressAndSecret` that would be included in the details passed to the review callback when a payment comes in. It would be used to identify which user or invoice the incoming payment chunks are for.

The most obvious way to do this would be to append the `keyId` to the `destinationAccount`. However, this value must be authenticated (and probably encrypted), because otherwise the sender would be able to modify it and potentially mess with the receiver. We could use an authenticated encryption scheme to encrypt the `keyId` and put it into the `destinationAccount`, but this would get quite long.

Should this be included as a feature in the PSK2 receiver, or should applications and application layer protocols that build on this library include such correlation IDs in the application data included in the PSK2 packet?

Another option would be to expose the `token` the receiver already appends to the `destinationAccount` to regenerate the `sharedSecret` in the response from `generateAddressAndSecret` and in the parameters passed to the review callback. That would allow  users to correlate incoming packets with address/secret pairs they gave out, but the user would need to remember the mapping (and it's possible they would have given multiple address/secret pairs out for the same `keyId`).

**Comment by sharafian** [comment]
> The most obvious way to do this would be to append the keyId to the destinationAccount. However, this value must be authenticated (and probably encrypted), because otherwise the sender would be able to modify it and potentially mess with the receiver.

I don't think that's a problem in all cases. For example, if the segment added on represented an invoice ID, it wouldn't matter if one sender paid another's invoice. Same goes for the receiver in Siren: you could change the segment that includes the receiver's ripple address, but it doesn't matter.

Providing it through this library might not be the best idea in case someone put important information into the ILP address not realizing it was unencrypted and unauthenticated, but it would at least be nice if the PSK module didn't reject when you added on additional ILP address segments (i.e. it should only look at the two segments after the address given by the ILDCP response)

**Comment by emschwartz** [comment]
Actually, I just realized that it would be easy to authenticate the extra segments. If we generate the shared secret from everything that's left after the ILDCP client address, tampering with the local part of the address would make it so the receiver wouldn't be able to decrypt the PSK packet.

**Comment by emschwartz** [comment]
Now my question is whether we need the random token at all when you pass in a `keyId`. That is used to generate the `sharedSecret` using an HMAC with a receiver secret. Would there be any problem if the user passed in a very short value or if calling `generateAddressAndSecret` twice with the same value returned the same `sharedSecret`? 

Maybe the argument against this would be that if you give the same value to two users, they would be able to read whatever data might be sent along with the other's requests.

**Comment by emschwartz** [comment]
Or maybe the stronger argument for always having a random part is that if you give two users the same `sharedSecret`, one of them would be able to fulfill the other's payments. If one of the users were collaborating with a connector in the network, they could reroute the payments somewhere else and fulfill them.
