### ISSUE TITLE
Multi-path payments?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-psk2#4]
Using multiple source plugins and figuring out which one has the cheapest rate

**Comment by emschwartz** [comment]
@justmoon made a good point that this would effectively replicate connector functionality so it's better to just run connector if you want to do this

**Comment by michielbdejong** [comment]
I thought our conclusion in https://github.com/interledger/rfcs/issues/340 was that only the sender (or only the first connector, depending on how you namei it) can do this, right? Intermediary connectors cannot know if the onward rate is cheap, because they don't know the destination amount.
