### ISSUE TITLE
Accept application data

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-psk2#5]
The question is how we should handle data split over multiple chunks. We can use the sequence to order them, but should receivers reject packets with duplicate sequences? What happens if you get them out of order or never get a specific packet in the middle?

**Comment by michielbdejong** [comment]
Why not just send all the application data in the first chunk?

**Comment by emschwartz** [comment]
Definitely an option, as long as the application data doesn't exceed the packet data limit (minus the overhead for the PSK2 header itself)

**Comment by michielbdejong** [comment]
For sending data from the receiver to the sender, all bets are off, you can always get a situation where the payment was successful, but the data transmission was not. So unless you're willing to pay unlimited money, adding retry mechanisms on the way back will not help guarantee anything. 

But on the way forward, i.e. sending data from the sender to the receiver, the receiver can refuse chunks that don't have the expected data chunk.
